/**
 * Editorial Norwegian bodies for the 4 tips articles (owner-supplied copy,
 * 01.10.2026). Index matches `d.tips.items`. Body markup: blank-line
 * paragraphs, `## ` for H2, `[text](/path/)` internal links (localized at render).
 */
export interface TipArticle { seoTitle: string; seoDescription: string; intro: string; body: string }

export const TIP_ARTICLES_NO: TipArticle[] = [
  {
    seoTitle: "Vinterhelg på Bjorli – ski, langrenn og lokale tips",
    seoDescription: "Planlegg en vinterhelg på Bjorli med ski, langrenn og pauser ved bakken. Få lokale tips til overnatting, skiutleie, Heiskroa og reisen hit.",
    intro: "En vinterhelg på Bjorli kan romme både alpint, langrenn og tid sammen rundt middagsbordet. Med noen enkle valg før avreise får du mer ut av dagene i fjellet.",
    body: "## Fredag: Gjør deg klar til første skidag\n\nVelg [overnatting](/overnatting/) ut fra det dere vil gjøre mest. For en helg med mye alpint er avstanden til bakken nyttig å sjekke. Skal dere også gå langrenn, bør dere undersøke hvor dere kommer inn på løypenettet.\n\nAvklar [skiutleie](/skiutleie/) før avreise hvis dere trenger utstyr. Intersport Bjorli ligger ved bakken, så dere kan hente utstyret i nærheten av der skidagen starter. Sjekk også [åpningstidene](/apningstider/) og ordne [heiskort](/heiskort/).\n\n## Lørdag: Finn rytmen i bakken\n\nSe på [løypekartet](/loypekart/) før dere starter. Velg bakker som passer ferdighetene, og la den første timen være en rolig oppvarming. Hvis noen trenger en trygg start eller vil bli bedre på ski, kan dere planlegge en time med [skiskolen](/skiskole/).\n\nAvtal et møtested for lunsj. Heiskroa og T-Kroken ved bakken er aktuelle steder å legge pausen når de holder åpent. En tydelig pause gjør det lettere å holde familien samlet og vurdere hvor mye energi som er igjen til ettermiddagen.\n\n## Søndag: Bytt ut heisen med langrenn\n\nSett av søndagen til [langrenn](/langrenn/) hvis dere ønsker variasjon. På Bjorli kan dere velge mellom turer i skogsterreng og mer åpne fjellområder når forholdene tillater det.\n\nSjekk løypepreparering og [vær og webkamera](/vaer-og-webkamera/) før dere velger tur. Med vind eller lite sikt kan en kortere tur i skjermet terreng være et bedre valg.\n\n## Planlegg reisen hjem\n\nBjorli har stasjon på Raumabanen og kan nås med tog via Dombås eller fra Åndalsnes. Sjekk aktuelle avganger og planlegg transporten mellom stasjonen og overnattingsstedet før dere reiser.",
  },
  {
    seoTitle: "Tog til Bjorli – 5 grunner til å velge Raumabanen",
    seoDescription: "Ta toget til Bjorli på Raumabanen. Les om stasjonen ved skisenteret, forbindelser via Dombås, skiutleie og utsikten på reisen fra Åndalsnes.",
    intro: "Bjorli er et av fjellstedene der jernbanen tar deg helt frem til bygda. Her er 5 grunner til å vurdere toget neste gang du planlegger en tur.",
    body: "## 1. Du kommer frem til Bjorli stasjon\n\nStasjonen ligger i bygda, i nærheten av skisenteret. Det gjør toget til et praktisk alternativ for en skitur, særlig hvis du velger [overnatting](/overnatting/) med kort vei videre.\n\nSjekk avstanden til akkurat ditt overnattingssted. Bagasje, barn og skiutstyr påvirker hvor enkelt den siste delen av reisen blir.\n\n## 2. Du kan reise via Dombås\n\nFra Oslo og Trondheim kan du planlegge reisen med forbindelse til Raumabanen på Dombås. Sjekk rutetider, byttetid og eventuelle trafikkendringer hos Entur eller SJ før du bestiller.\n\nLegg inn litt margin dersom dere reiser med barn eller mye bagasje.\n\n## 3. Reisen fra Åndalsnes byr på utsikt\n\nKommer du fra Åndalsnes, går reisen gjennom Romsdalen. På denne delen av Raumabanen finner du landskapet ved Trollveggen og Kylling bru.\n\nDet kan gjøre reisen til en del av opplevelsen. Velg en avgang med dagslys hvis utsikten er viktig for deg.\n\n## 4. Du kan leie ski ved bakken\n\nDu trenger ikke ta med alt utstyret hjemmefra. Intersport Bjorli tilbyr [skiutleie](/skiutleie/) ved skisenteret.\n\nAvklar hva dere trenger og hvordan utleien fungerer før avreise. Da blir det enklere å reise med mindre bagasje.\n\n## 5. Alle kan ta pause underveis\n\nPå toget kan dere spise matpakke, lese eller planlegge dagene sammen. Se gjerne på [løypekartet](/loypekart/), sjekk [åpningstidene](/apningstider/) og avklar om noen ønsker [skiskole](/skiskole/).\n\nPlanlegg hjemreisen samtidig. Kontroller aktuelle avganger og transporten til stasjonen, så får dere en tydelig ramme rundt oppholdet.",
  },
  {
    seoTitle: "Familieferie på Bjorli – ski, pumptrack og turer",
    seoDescription: "Planlegg familieferie på Bjorli med skiskole, pumptrack og lokale turmål. Få tips til Lesjaskogsvatnet, Sagelva og overnatting for familien.",
    intro: "På Bjorli kan familien samle ski, sykling og små utflukter i samme ferie. Velg aktivitetene etter årstid og barnas erfaring, og la det være plass til pauser.",
    body: "## Vinter: Start med mestring i bakken\n\nFor barn som skal lære å stå på ski, er en rolig start viktig. Planlegg tid i barneområdet og vurder [skiskole](/skiskole/) hvis dere vil ha hjelp med de første svingene.\n\nTrenger dere utstyr, ligger Intersport Bjorli ved bakken og tilbyr [skiutleie](/skiutleie/). Avtal korte økter og et fast møtested for pauser. Heiskroa og T-Kroken er aktuelle stopp når de holder åpent.\n\n## Sommer: Prøv pumptracken\n\nPumptracken på Bjorli gir barna mulighet til å øve på balanse og sykkelferdigheter. Start rolig, bruk hjelm og la barna bli kjent med banen før de øker farten.\n\nDette kan være en fin aktivitet mellom lengre utflukter. En kort sykkeløkt krever mindre planlegging enn en hel dag på tur.\n\n## Ta en utflukt til Lesjaskogsvatnet\n\nLesjaskogsvatnet er et aktuelt turmål når dere vil ha en dag ved vannet. Undersøk muligheten for kano eller båt hos lokale tilbydere før dere drar.\n\nVelg aktivitet etter barnas erfaring og værforholdene. Bruk redningsvest på vannet, og sjekk fiskekort dersom dere vil fiske.\n\n## Opplev vannkraft på Sagelva\n\nSagelva vasskraftsenter ved Stueflotten viser hvordan vannkraft har vært brukt til blant annet sag og kvern. Et besøk kan passe for barn som liker å se hvordan ting virker.\n\nSjekk åpningstider og omvisninger før dere planlegger turen.\n\n## Velg fjelltur etter familien\n\nRånåbue på Rånåkollen er et lokalt turmål for familier som er vant til å gå. Turen har bratte partier, så vurder formen og erfaringen til den yngste før dere velger den.\n\nFinn [overnatting](/overnatting/) som passer familiens behov, og bruk [familiesiden](/familie/) som utgangspunkt for oppholdet.",
  },
  {
    seoTitle: "Bjorli om sommeren – Rånåkollen, padling og sykling",
    seoDescription: "Opplev sommeren på Bjorli med tur til Rånåbue, padling på Lesjaskogsvatnet og besøk på Sagelva. Få konkrete tips til en ferie mellom fjell og dal.",
    intro: "Sommeren på Bjorli gir deg tilgang til fjellturer, vann og utflukter gjennom dalene rundt bygda. Her er forslag til 3 dager med ulike opplevelser.",
    body: "## Dag 1: Gå til Rånåbue på Rånåkollen\n\nRånåbue er et turmål som gir deg et konkret mål for fjellturen. Stien opp har bratte partier, så sett av god tid og velg dagen etter værmeldingen.\n\nTa med matpakke, drikke og klær for skiftende vær. Følg merket rute, lukk grinder etter deg og vis hensyn til dyr på beite.\n\n## Dag 2: Utforsk Lesjaskogsvatnet\n\nLegg neste dag til Lesjaskogsvatnet. Undersøk muligheten for å leie kano eller båt, og velg en tur som passer erfaringen deres.\n\nBruk redningsvest og vurder vindforholdene før dere legger ut. Vil dere fiske, må dere sjekke hvilke fiskekort og regler som gjelder.\n\nEn dag ved vannet passer også som en roligere pause mellom fjellturene.\n\n## Dag 3: Besøk Sagelva eller ta en sykkeløkt\n\nSagelva vasskraftsenter ved Stueflotten gir et innblikk i lokal historie og bruk av vannkraft. Sjekk sesongens åpningstider og omvisninger før dere drar.\n\nVil dere holde dere på Bjorli, kan pumptracken være et alternativ for en kortere aktivitet. Bruk hjelm og tilpass farten til ferdighetene.\n\n## Sett av tid til Romsdalen\n\nHar dere flere dager, kan dere reise vestover mot Åndalsnes. Raumabanen gir mulighet til å oppleve dalen fra toget. Sjekk aktuelle avganger og returmuligheter før dere planlegger en dagstur.\n\n## Bruk Bjorli som base\n\nVelg [overnatting](/overnatting/) ut fra hvem dere reiser med og aktivitetene dere vil prioritere. Bruk [tipsoversikten](/tips/) for flere ideer, og la vær og dagsform styre rekkefølgen på turene.",
  },
];
