/**
 * Generate `public/_headers` for Cloudflare Pages based on the
 * current deploy environment.
 *
 * Production detection (in priority order):
 *   1. `SITE_URL === 'https://bjorli.no'`
 *   2. `CF_PAGES_BRANCH === 'main'`  (Cloudflare Pages production branch)
 *
 * If neither is true the deploy is treated as Preview/staging and the
 * file emits `X-Robots-Tag: noindex, nofollow` for every path so that
 * `*.pages.dev` preview hosts are never indexed even if a crawler
 * ignores `robots.txt`. SPA fallback continues to live in
 * `public/_redirects` — this file only sets response headers.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const PRODUCTION_SITE_URL = 'https://bjorli.no';
const PRODUCTION_BRANCH = 'main';

const siteUrl = process.env.SITE_URL;
const branch = process.env.CF_PAGES_BRANCH;

const isProduction =
  siteUrl === PRODUCTION_SITE_URL ||
  (!siteUrl && branch === PRODUCTION_BRANCH);

const productionHeaders = `# Cloudflare Pages headers — production (indexable).
# Generated by scripts/build-deploy-headers.ts. Do not hand-edit.

/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin

# Legacy WordPress asset paths: dead /wp-content/* files must never be
# indexed even while they still return 404 or are served from cache.
/wp-content/*
  X-Robots-Tag: noindex, nofollow
/wp-includes/*
  X-Robots-Tag: noindex, nofollow
`;

const previewHeaders = `# Cloudflare Pages headers — preview/staging (NOT indexable).
# Generated by scripts/build-deploy-headers.ts. Do not hand-edit.
#
# SITE_URL=${siteUrl ?? ''}  CF_PAGES_BRANCH=${branch ?? ''}
# Treated as non-production: emitting X-Robots-Tag: noindex, nofollow
# so *.pages.dev hosts cannot be indexed by search engines or AI crawlers.

/*
  X-Robots-Tag: noindex, nofollow
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
`;

const body = isProduction ? productionHeaders : previewHeaders;
writeFileSync(resolve('public/_headers'), body);
console.log(
  `_headers written — ${isProduction ? 'PRODUCTION (indexable)' : 'PREVIEW (noindex)'}` +
    ` (SITE_URL=${siteUrl ?? 'unset'}, CF_PAGES_BRANCH=${branch ?? 'unset'}).`,
);